# Generated by Django 3.2.8 on 2021-10-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPaper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='porsCategory',
            new_name='postCategory',
        ),
    ]
